# Generated by Django 5.1.6 on 2025-02-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.FloatField()),
                ('fire_alert', models.BooleanField(default=False)),
                ('cattle_alert', models.BooleanField(default=False)),
                ('pump_status', models.BooleanField(default=False)),
                ('led_status', models.BooleanField(default=False)),
            ],
        ),
    ]
