# Generated by Django 5.1.6 on 2025-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
