# Generated by Django 5.1.6 on 2025-02-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensordata_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=56),
            preserve_default=False,
        ),
    ]
